language: java

jdk:
  - oraclejdk8
  - openjdk7

env:
  - SONARHOME=/tmp/sonarqube-4.5.2
  - SONARHOME=/tmp/sonarqube-4.5.4
  - SONARHOME=/tmp/sonarqube-5.0.1
  - SONARHOME=/tmp/sonarqube-5.1
  
before_install:
        - travis_retry sudo apt-get install libboost-dev libboost-test-dev
        
install:
        - cd /tmp
        - travis_retry wget http://dist.sonar.codehaus.org/sonarqube-4.5.2.zip
        - unzip sonarqube-4.5.2.zip        
        - travis_retry wget http://dist.sonar.codehaus.org/sonarqube-4.5.4.zip
        - unzip sonarqube-4.5.4.zip        
        - travis_retry wget http://dist.sonar.codehaus.org/sonarqube-5.0.1.zip
        - unzip sonarqube-5.0.1.zip
        - travis_retry wget http://dist.sonar.codehaus.org/sonarqube-5.1.zip
        - unzip sonarqube-5.1.zip        
        - travis_retry wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
        - unzip sonar-runner-dist-2.4.zip
        - cd -

before_script:
        - travis_retry sudo pip install requests
        - travis_retry sudo pip install behave
        - travis_retry sudo pip install colorama

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin behave
